export const SET_CHARACTERS = 'SET_CHARACTERS';
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const SET_CHAR_CARD_VISIBLE = 'SET_CHAR_CARD_VISIBLE';
export const SET_CHAR_CARD_INFO = 'SET_CHAR_CARD_INFO';
